### ISSUE TITLE
SPA session and API key authentication

### ISSUE THREAD

**Issue by elumalai** [goji/ctx-csrf#4]
Our REST API will be used by our SPA web client as well as our customers. API will first look in the authorization header for API key and check for a session cookie if authorization header was missing.What would be the recommended approach if we want to skip the CSRF middleware if the API key is available.

@elithrar

**Comment by elithrar** [comment]
You can wrap the CSRF middleware (i.e. call CSRF := csrf.Protect(key,
opts...)) in middleware that checks for the presence of an Authorization
header.

Something like:

// goji.UseC(CheckAuthorization(CSRF))
func CheckAuthorization(mw func(goji.Handler) goji.Handler)
func(goji.Handler) goji.Handler { ... }

The alternative would be to have ctx-csrf inspect the request context for
the presence of a goji.csrf.Bypass key with the value of 'true' on a
per-request basis. Your middleware could set that as long as it's added to
the middleware stack before ctx-csrf is.

**Comment by elumalai** [comment]
@elithrar Thank you. Would you be interested in providing such option in ctx-csrf as described in the second approach ?

**Comment by elithrar** [comment]
Yep, I'll see about getting this done by the end of the weekend!

**Comment by elithrar** [comment]
@elumalai https://github.com/goji/ctx-csrf/pull/5 should help: let me know if that's not what you were expecting.

**Comment by elumalai** [comment]
@elithrar  Thank you.. This should work.

**Comment by elithrar** [comment]
Merged. Update your local copy and you should be good to go.
